[project]
name = "py_json2htmlresume"
version = "0.1.0"
description = "Add a short description here"
authors = ["Theo van der Sluijs <theo@vandersluijs.nl>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
buildResume = "python main.py"

[dependencies]
jinja2 = ">=3.1.4,<3.2"
docx-mailmerge = ">=0.5.0,<0.6"
requests = ">=2.32.3,<2.33"
css-html-js-minify = ">=2.5.5,<3"
